MiquelSiteBundle:
    resource: "@MiquelSiteBundle/Resources/config/routing.yml"
    prefix:   /

MiquelLinkBundle:
    resource: "@MiquelLinkBundle/Resources/config/routing.yml"
    prefix:   /links

MiquelMemoBundle:
    resource: "@MiquelMemoBundle/Resources/config/routing.yml"
    prefix:   /memo

MiquelCvBundle:
    resource: "@MiquelCvBundle/Resources/config/routing.yml"
    prefix:   /cv

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
