MiquelLink_Accueil:
    pattern:  /
    defaults: { _controller: MiquelLinkBundle:Link:index }
        
MiquelLink_Voir:
    pattern: /voir/{id}
    defaults: { _controller:MiquelLinkBundle:Link:voir }
    requirements:
        id: \d+
    
MiquelLink_Ajouter:
    pattern:  /ajouter
    defaults: { _controller: MiquelLinkBundle:Link:ajouter }
    
MiquelLink_Modifier:
    pattern:  /modifier/{id}
    defaults: { _controller: MiquelLinkBundle:Link:modifier }
    requirements: 
        id: \d+
    
MiquelLink_Supprimer:
    pattern:  /supprimer/{id}
    defaults: { _controller: MiquelLinkBundle:Link:supprimer }
    requirements:
        id: \d+