<?php

namespace Miquel\MemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{

	public function getDefaultCategories()
	{
		$queryBuilder = $this->createQueryBuilder('a');
		
		// Méthode équivalente, mais plus longue :
		$queryBuilder = $this->_em->createQueryBuilder()
		  ->select('a')
		  ->from($this->_entityName, 'a'); // Dans un repository, $this->_entityName est le namespace de l'entité gérée
																// Ici, il vaut donc Sdz\BlogBundle\Entity\Article
		
		// On a fini de construire notre requête.
		
		// On récupère la Query à partir du QueryBuilder
		$query = $queryBuilder->getQuery();
		
		// On récupère les résultats à partir de la Query
		$resultats = $query->getResult();
		
		// On retourne ces résultats
		return $resultats;
	}
    
    public function getAllFiches(Categorie $categorie = null)
    {
        $qb = $this->createQueryBuilder('c'); // 'c' = la table Categorie
        
        if (!is_null($categorie))
            $qb->join('c.fiches', 'f', 'WITH', 'c.id = ' . $categorie->getId()); // On demande une jointure sur Categorie.fiches avec la table Fiche (f)
        
        else
            $qb->join('c.fiches', 'f');
            
         $qb->addSelect('f');

        return $qb->getQuery()
                            ->getResult();
    }

}